apiVersion: 1
groups:
    - orgId: 1
      name: error rate
      folder: UserService
      interval: 1m
      rules:
        - uid: eee524d5-c780-40b6-bcba-df7d33d8c882
          title: Errors(RPM)
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: prometheus
              model:
                datasource:
                    type: prometheus
                    uid: prometheus
                editorMode: code
                expr: 'sum(increase(nginx_ingress_controller_requests{exported_service="user-service-release-user-service-api",status=~"4.+|5.+"}[1m])) '
                instant: false
                interval: ""
                intervalMs: 30000
                legendFormat: '{{action}}'
                maxDataPoints: 43200
                range: true
                refId: A
            - refId: B
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1000
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: bb1a80f3-79ef-4a41-a807-d712d79e71f0
          panelId: 6
          noDataState: NoData
          execErrState: Error
          for: 5m
          annotations:
            __dashboardUid__: bb1a80f3-79ef-4a41-a807-d712d79e71f0
            __panelId__: "6"
          isPaused: false
    - orgId: 1
      name: latency
      folder: UserService
      interval: 1m
      rules:
        - uid: fae2ee67-4a33-4808-b876-fe9c2eff6a08
          title: Latency (response time) 0.99 quantile Alert
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: prometheus
              model:
                datasource:
                    type: prometheus
                    uid: prometheus
                editorMode: code
                exemplar: false
                expr: histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service="user-service-release-user-service-api"}[2m])) by (le))
                instant: false
                interval: ""
                intervalMs: 30000
                key: Q-695060ac-3bd5-4390-b203-580cd9797394-0
                legendFormat: user-service
                maxDataPoints: 43200
                range: true
                refId: A
            - refId: B
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0.03
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: bb1a80f3-79ef-4a41-a807-d712d79e71f0
          panelId: 3
          noDataState: NoData
          execErrState: Error
          for: 5m
          annotations:
            __dashboardUid__: bb1a80f3-79ef-4a41-a807-d712d79e71f0
            __panelId__: "3"
          isPaused: false
