{
 "title": "UserServiceApi",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency (response time) 0.5 quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{action!=\"\"}[2m])) by (le,action))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Traffic(RPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{action!=\"\"}[2m])) by(action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Latency (response time) 0.95 quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{action!=\"\"}[2m])) by (le,action))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Errors(RPM)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total{action!=\"\",code=~\"4.+|5.+\"}[1m])) by(code)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Latency (response time) 0.99 quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{action!=\"\"}[2m])) by (le,action))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total{action!=\"\",code=~\"4.+|5.+\"}[1m])) / sum(increase(http_requests_received_total{action!=\"\"}[1m]))"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{service=\"user-service-release-user-service-api\"}",
     "legendFormat": "PodName = {{pod}}"
    }
   ]
  }
 ]
}