{
 "title": "UserServiceNginxIngressController",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency (response time) 0.5 quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"user-service-release-user-service-api\"}[2m])) by (le))",
     "legendFormat": "user-service"
    }
   ]
  },
  {
   "title": "Traffic(RPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_service=\"user-service-release-user-service-api\"}[2m])) by(exported_service)",
     "legendFormat": "user-service"
    }
   ]
  },
  {
   "title": "Latency (response time) 0.95 quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"user-service-release-user-service-api\"}[2m])) by (le))",
     "legendFormat": "user-service"
    }
   ]
  },
  {
   "title": "Errors(RPM)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{exported_service=\"user-service-release-user-service-api\",status=~\"4.+|5.+\"}[1m])) by(status)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Latency (response time) 0.99 quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"user-service-release-user-service-api\"}[2m])) by (le))",
     "legendFormat": "user-service"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{exported_service=\"user-service-release-user-service-api\",status=~\"4.+|5.+\"}[1m])) / sum(increase(nginx_ingress_controller_requests{exported_service=\"user-service-release-user-service-api\"}[1m]))"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{service=\"user-service-release-user-service-api\"}",
     "legendFormat": "PodName = {{pod}}"
    }
   ]
  },
  {
   "title": "UserService Pods Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"user-service-release-user-service-api.*\"}) by(pod) ",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "UserService Pods CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"user-service-release-user-service-api.*\"}[5m])) by(pod)",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}