# Запуск команд: kubectl create namespace ingress-nginx
# helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx/ 
# helm repo update 
# helm install nginx ingress-nginx/ingress-nginx --namespace ingress-nginx -f nginx_ingress.yaml
controller:
  name: controller
  kind: DaemonSet
  containerName: controller
  
  containerPort:
    http: 80
    https: 443
  
  reportNodeInternalIp: true

  hostPort:
    enabled: false
    ports:
      http: 80
      https: 443

  service:
    enabled: true
    ports:
      http: 8081
      https: 8443
    targetPorts:
      http: http
      https: https
    type: LoadBalancer