apiVersion: v1
kind: Secret
metadata:
  name: {{ template "user-service-api.secretName" . }}
  labels:
    app: {{ template  "user-service-api.name" . }}
    chart: {{ template "user-service-api.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
  appsettings.secrets.Production.json: |
    {
      "ConnectionStrings": {
        "UserService": "Host=dev-pg-postgresql;Port=5432;Pooling=true;User ID=postgres;Password=1qaz!QAZ;Database=otus_userservice"
      }
    }