apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-configs
data:
  appsettings.Production.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "Kestrel": {
        "Endpoints": {
          "Http": {
            "Url": "http://[::]:8000"
          }
        }
      },
      "DeployOptions": {
        "UseAutoMigrate": true
      }
    }