controller:
  name: controller
  kind: DaemonSet
  containerName: controller
  
  containerPort:
    http: 80
    https: 443
  
  reportNodeInternalIp: true

  hostPort:
    enabled: false
    ports:
      http: 80
      https: 443

  service:
    enabled: true
    ports:
      http: 80
      https: 443
    targetPorts:
      http: http
      https: https
    type: LoadBalancer