apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
type: Opaque
stringData:
  appsettings.secrets.Production.json: |
    {
      "ConnectionStrings": {
        "UserService": "Host=dev-pg-postgresql;Port=5432;Pooling=true;User ID=postgres;Password=1qaz!QAZ;Database=otus_userservice"
      }
    }